name: Build firmware
on:
  push:
  pull_request:
jobs:
  build_fw:
    name: "Build firmware"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install ESP-IDF
        uses: ./.github/actions/setup-esp-idf
        with:
          version: v4.3
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python-yaml # For Duktape configuration
      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          cd firmware
          cp main/credentials_template.hpp main/credentials.hpp
          idf.py build
          idf.py size
  build_doc:
    name: "Build documentation"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo pip3 install mkdocs
      - name: "Build"
        run: |
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: site
          retention-days: 14
  deploy:
    name: "Deploy GH Pages"
    runs-on: ubuntu-20.04
    needs: build_doc
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout # Required for GH-pages deployment
        uses: actions/checkout@v2
      - name: "Download documentation"
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: documentation
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: documentation
          single-commit: true



